name: Test and lint

on: [push]

jobs:

  clojure:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.4+7.0.LTS'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435              # Clojure CLI based on tools.deps
          clj-kondo: 2024.02.12        # Clj-kondo
          cljfmt: 0.12.0              # cljfmt
          
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Test
        run: clojure -Mkaocha-ci --no-capture-output
        
      - name: Clj-kondo
        run: clj-kondo --lint src:test

      - name: Cljfmt
        run: cljfmt check src test
